### ISSUE TITLE
Stuck at Loading 100% with phpBB 3.2.5

### ISSUE THREAD

**Issue by MixingOnBeat** [BoardTools/upload#47] opened 2018-12-26 21:27 UTC
Updated to phpBB 3.2.5 and it seems it broke this extension.

When I upload or try to install an extension, it gets stuck at 100% Loading with the green bar animated.

Using 3.2.0-dev

**Comment by lavigor** [comment] 2018-12-27 08:04
Hi,
thank you for your report, I've already received it on phpbb.com.

Sorry for not answering, a bit busy now.
An update will be made soon, sorry for the delay.

Best regards,
Igor

**Comment by lavigor** [comment] 2018-12-30 00:19
@MixingOnBeat sorry once again for the delay.
Fixed in `develop-3.2.0`.

**Closed as completed by lavigor** 2018-12-30 00:19 UTC

**Comment by lavigor** [comment] 2018-12-30 16:09
For future reference: the error was caused by the update of jQuery in phpBB 3.2.5 to version 1.12.4 that was no longer compatible with `ajaxSubmit` method of jQuery Form plugin described in [this issue](https://github.com/jquery-form/form/issues/495).
